<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-CHABA.DayCare-36c870d4-100f-43fe-9d3d-d0e14899ce14</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.24" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.24" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.24" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.24" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.24" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Constants\" />
    <Folder Include="Helpers\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Models\Finance\" />
    <Folder Include="Models\Reports\" />
    <Folder Include="Services\Attendance\" />
    <Folder Include="Services\Dashboard\" />
    <Folder Include="Services\Guardian\" />
    <Folder Include="Services\Child\" />
    <Folder Include="Services\Teacher\" />
    <Folder Include="Services\Payment\" />
    <Folder Include="ViewModels\Child\" />
    <Folder Include="ViewModels\Guardian\" />
    <Folder Include="ViewModels\Payment\" />
    <Folder Include="ViewModels\Teacher\" />
  </ItemGroup>

</Project>
